#! /bin/bash

### GLOBALS
name='[vscode installer] '
loc='/usr/lib/code-insider'
link='LinkId=723968'
download='index.html?'$link


## Clear out latest builds and downloads
echo $name 'Prepping for download...'
rm -Rf $loc/latest
rm -f $loc/index.*

## Get latest 
echo $name 'Downloading latest VSCode...'
wget https://go.microsoft.com/fwlink/?$link -P $loc

## Unzip tar file
echo $name 'Updating files...'
echo $name 'Unzipping' $loc/$download
tar xfz $loc/$download -C $loc
echo $name 'Unzipped'

echo $name 'Cleaning up'
rm $loc/$download

## Move contents to latest
mv $loc/VSCode-linux-x64/ $loc/latest
echo $name 'Installation complete!'
exit;
