#! /bin/bash

### GLOBALS
CURRENT_DIRECTORY=$(pwd)
SCRIPT_NAME="vscode_install_latest"
GLOBAL_SCRIPT_REPO="/usr/bin"
APP="[vscode installer] "
APP_DIRECTORY="/usr/lib/code-insider"
LATEST_APP_DIRECTORY=$APP_DIRECTORY"/latest"
APP_EXEC="/usr/lib/code-insider/latest/code-insiders"
DOWNLOAD_LINKID="LinkId=723968"
DOWNLOAD="index.html?"$DOWNLOAD_LINKID


## Clear out latest builds and downloads
echo $APP "Prepping for download..."
rm -Rf $APP_DIRECTORY/latest
rm -f $APP_DIRECTORY/index.*

## Get latest 
echo $APP "Downloading latest VSCode..."
wget https://go.microsoft.com/fwlink/?$DOWNLOAD_LINKID -P $APP_DIRECTORY

## Unzip tar file
echo $APP "Updating files..."
echo $APP "Unzipping" $APP_DIRECTORY/$DOWNLOAD
tar xfz $APP_DIRECTORY/$DOWNLOAD -C $APP_DIRECTORY
echo $APP "Unzipped as "$APP_DIRECTORY/

echo $APP "Cleaning up"
rm $APP_DIRECTORY/$DOWNLOAD

# Update permissions
echo $APP "Updating application permissions"
chmod 755 $APP_EXEC

# Remove and re-add global pointers
echo $APP "Updating application global symlinks"
rm "/usr/bin/code"
rm "/usr/bin/code-insiders"
ln -s $APP_EXEC "/usr/bin/code"
ln -s $APP_EXEC "/usr/bin/code-insiders"

## Add global point to this script
echo $APP "Adding vscode_install_latest to global scope"
ln -s $CURRENT_DIRECTORY"/"$SCRIPT_NAME $GLOBAL_SCRIPT_REPO"/"$SCRIPT_NAME


## Move contents to latest
echo $APP "Moving files "$APP_DIRECTORY"/VSCode-linux-x64/ into "$LATEST_APP_DIRECTORY
mv $APP_DIRECTORY/VSCode-linux-x64/ $LATEST_APP_DIRECTORY
echo $APP "Installation complete!"
exit;
